# Generated by Django 5.2.6 on 2025-09-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_quantity_orderitem_qty_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
